version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  hygiene:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run:
                name: lint
                command: yarn lint
            - run:
                name: type check
                command: yarn tsc
            - run:
                name: unit test
                command: yarn test:ci
            - run:
                name: build
                command: yarn build
workflows:
  build-and-test:
    jobs:
      - hygiene
